import { WHATSAPP_DISPLAY } from "../site";
import type { ChatProduct } from "./facts";

/**
 * The check that runs after the model has spoken.
 *
 * Everything upstream of this file asks the model to stay grounded. This file
 * assumes it did not. It is the difference between an assistant that is
 * usually accurate and one that cannot quote a price we do not charge.
 *
 * Two things get verified, chosen because they are the two ways an invented
 * product actually reaches a customer:
 *
 *   1. CITATIONS. Every [P1]-style tag must point at a row that came back from
 *      the search. A tag outside that range means the model wrote about a
 *      product that does not exist.
 *   2. FIGURES. Every number of four digits or more must already appear in
 *      what we told the model, or in what the customer themselves typed.
 *      Prices are the payload of a furniture hallucination — "the Milano
 *      recliner is Rs 45,000" is a sentence a customer will act on, turn up at
 *      Shen Gul Plaza holding, and be wrong about.
 *
 * A failure is not repaired, it is DISCARDED. Editing a reply that has already
 * demonstrated it is inventing things leaves the rest of the sentence — which
 * was generated by the same lapse — in place. The caller swaps in a reply
 * composed from the rows instead. Boring and correct beats fluent and wrong.
 *
 * WHAT THIS DOES NOT CATCH, stated plainly so nobody reads more into it than
 * is there: a bare invented product NAME, carrying no price and no citation,
 * in prose. Recognising that would mean deciding whether an arbitrary
 * capitalised phrase is a product, which cannot be done reliably. What is
 * guaranteed is narrower and worth more — no product data, link or figure
 * reaches a customer unless it came from a row. An invented name with nothing
 * attached is embarrassing; an invented PRICE is what a customer acts on, and
 * that is closed.
 */

/** `[P3]` — the only way a reply is allowed to point at a product. */
const CITATION_PATTERN = /\[P(\d+)\]/g;

/**
 * Citations, as the model actually writes them.
 *
 * Found the hard way against openai/gpt-oss-120b, which was asked for `[P1]`
 * and returned `【P1】` — CJK fullwidth brackets. That is not cosmetic. A
 * citation the pattern above does not match is a citation that is never range
 * checked, so a fabricated `【P9】` would sail past the very check written to
 * catch it, and the UI would render the brackets as literal text next to a
 * product it cannot resolve.
 *
 * So the reply is normalised into the canonical form BEFORE anything is
 * verified. Normalising can only expose a bad citation, never create a good
 * one: `【P9】` becomes `[P9]` and then fails the range check exactly as it
 * should. Fullwidth and half-width brackets, parentheses, stray inner spaces
 * and a lowercase p are all folded in.
 */
const CITATION_VARIANTS = /[[(【〔（]\s*[Pp]\s*(\d+)\s*[\])】〕）]/g;

/**
 * Invisible characters, stripped before anything else looks at the text.
 *
 * The third variant of the same surprise, and the sneakiest: a reply came back
 * reading `[​P1]` with a ZERO-WIDTH SPACE (U+200B) between the bracket and the
 * P. It is indistinguishable from `[P1]` on screen and in a log, and JavaScript
 * `\s` does not match it — U+200B is a format character, not whitespace — so
 * the variant pattern above walks straight past it and the citation is never
 * range checked.
 *
 * Nothing in a customer-facing furniture answer needs a zero-width joiner, so
 * these are removed outright rather than folded to a space.
 */
const INVISIBLES = /[​-‍⁠﻿]/g;

/** Canonicalise citations. Exported because the caller returns this text. */
export function normaliseCitations(reply: string) {
  return reply
    .replace(INVISIBLES, "")
    .replace(CITATION_VARIANTS, (_match, ref: string) => `[P${Number(ref)}]`);
}

/**
 * Digit runs, commas included, so "Rs 118,000" is read as one number rather
 * than as 118 and 000.
 */
const NUMBER_PATTERN = /\d[\d,]*/g;

/**
 * Fold typographic whitespace to a plain space before any number is read.
 *
 * THIS IS THE WHOLE TRICK, and it cost a round of false rejections to learn.
 * The check compares figures in the reply against figures in the fact block,
 * so the two only have to be extracted the SAME way — but they are written by
 * different authors. lib/site.ts writes the WhatsApp number with ASCII spaces;
 * gpt-oss-120b repeats it back with U+202F narrow no-break spaces. A pattern
 * that treats one as a separator and not the other reads "+92 300 905 9052"
 * as 9052 on one side and as 923009059052 on the other, and then rejects a
 * perfectly grounded reply for quoting our own phone number.
 *
 * Normalising both sides first makes the comparison symmetric, which is the
 * only property that actually matters here.
 *
 * KNOWN GAP, accepted deliberately: a price grouped with spaces rather than a
 * comma — "Rs 45 000" — reads as 45 and 000, both under the floor, and goes
 * unchecked. Treating a space as a thousands separator would close that and
 * open something worse, because the phone number is space-grouped too and the
 * two conventions are indistinguishable without knowing which is which. Comma
 * grouping is what the fact block and every observed reply actually use.
 */
function foldSpaces(text: string) {
  return text.replace(/[    ]/g, " ");
}

/**
 * Below this, a number is not a price.
 *
 * Deliberately not zero. Dimensions ("84\" W x 36\" D"), seat counts, storey
 * numbers and years-of-experience are all small, all harmless, and all
 * routinely paraphrased rather than copied — checking them would reject good
 * replies for saying "a three seater" when the fact block said "3-Seater".
 * Four digits is where a number starts being a rupee figure in this catalogue,
 * whose cheapest item is Rs 18,500.
 */
const SIGNIFICANT_FIGURE = 1000;

/**
 * Every figure in `text` big enough to be a price.
 *
 * Exported because lib/ai/summary.ts needs exactly this, applied to a product
 * row instead of a chat fact block. Two copies of "what counts as a number
 * here" would drift the first time one of them learned about a new separator,
 * and the whole guarantee rests on both sides of a comparison extracting
 * identically.
 */
export function significantFiguresIn(text: string): Set<number> {
  const found = new Set<number>();

  for (const match of foldSpaces(text).matchAll(NUMBER_PATTERN)) {
    const value = Number(match[0].replace(/,/g, ""));
    if (Number.isFinite(value) && value >= SIGNIFICANT_FIGURE) found.add(value);
  }

  return found;
}

export type GroundingVerdict =
  | { grounded: true; citations: number[] }
  | { grounded: false; reason: string };

/**
 * @param reply      the model's reply, ALREADY through normaliseCitations()
 * @param facts      every fact block the model was shown, concatenated
 * @param userText   the CURRENT message only — see the note below
 * @param products   the rows retrieved for this turn
 */
export function checkGrounding(
  reply: string,
  facts: string,
  userText: string,
  products: ChatProduct[],
): GroundingVerdict {
  // Citations first: a bad one is unambiguous evidence, and cheap to find.
  const citations: number[] = [];

  for (const match of reply.matchAll(CITATION_PATTERN)) {
    const ref = Number(match[1]);
    if (!Number.isInteger(ref) || ref < 1 || ref > products.length) {
      return {
        grounded: false,
        reason: `cited [P${match[1]}] but only ${products.length} product(s) were retrieved`,
      };
    }
    if (!citations.includes(ref)) citations.push(ref);
  }

  // WHY userText IS THE CURRENT MESSAGE AND NOT THE CONVERSATION. The client
  // supplies the history, so a crafted request can plant an "assistant" turn
  // reading "the Milano recliner is Rs 45,000". Whitelisting numbers from
  // history would let that request pre-authorise its own hallucination — the
  // model repeats the planted figure and the check waves it through. The
  // customer's own current sentence is safe to allow because the reply needs
  // to be able to quote a budget back ("nothing under Rs 15,000, but…").
  const allowed = new Set([...significantFiguresIn(facts), ...significantFiguresIn(userText)]);
  const used = significantFiguresIn(reply);

  for (const value of used) {
    if (!allowed.has(value)) {
      return {
        grounded: false,
        reason: `stated the figure ${value}, which appears in no retrieved product and in no business fact`,
      };
    }
  }

  return { grounded: true, citations };
}

/**
 * The reply used when the model's own is discarded.
 *
 * Written from rows, so it cannot be wrong. It is plainer than a generated
 * answer and it is meant to be: this path only runs after something has gone
 * wrong, and the priority shifts from sounding helpful to being correct and
 * getting the customer to a human.
 *
 * Also the reply for a NOT_CONFIGURED or dead Groq on a message we could still
 * search — the catalogue works even when the assistant does not.
 */
export function fallbackReply(products: ChatProduct[]): string {
  if (products.length === 0) {
    return [
      "I could not find anything matching that in our online catalogue.",
      "That does not necessarily mean we cannot do it — we build custom pieces to your own measurements in our own workshop.",
      `Message us on WhatsApp at ${WHATSAPP_DISPLAY} and we will tell you what is possible.`,
    ].join(" ");
  }

  const lines = products.map(
    (product) =>
      `${product.name} [P${product.ref}] — ${product.priceLabel}, ${product.stockLabel.toLowerCase()}`,
  );

  return [
    "Here is what we have on the website that matches:",
    lines.join("\n"),
    `To confirm availability or arrange a look at the showroom, message us on WhatsApp at ${WHATSAPP_DISPLAY}.`,
  ].join("\n");
}
